// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for BookingStatus.
const (
	Cancelled BookingStatus = "cancelled"
	Completed BookingStatus = "completed"
	Confirmed BookingStatus = "confirmed"
)

// Valid indicates whether the value is a known member of the BookingStatus enum.
func (e BookingStatus) Valid() bool {
	switch e {
	case Cancelled:
		return true
	case Completed:
		return true
	case Confirmed:
		return true
	default:
		return false
	}
}

// Booking defines model for Booking.
type Booking struct {
	AttendeesCount int                `json:"attendees_count"`
	CreatedAt      time.Time          `json:"created_at"`
	Description    *string            `json:"description,omitempty"`
	EndTime        time.Time          `json:"end_time"`
	Id             openapi_types.UUID `json:"id"`
	RoomId         openapi_types.UUID `json:"room_id"`
	StartTime      time.Time          `json:"start_time"`
	Status         BookingStatus      `json:"status"`
	Title          string             `json:"title"`
	UpdatedAt      time.Time          `json:"updated_at"`
	UserId         openapi_types.UUID `json:"user_id"`
}

// BookingStatus defines model for Booking.Status.
type BookingStatus string

// BookingCreateRequest defines model for BookingCreateRequest.
type BookingCreateRequest struct {
	AttendeesCount *int               `json:"attendees_count,omitempty"`
	Description    *string            `json:"description,omitempty"`
	EndTime        time.Time          `json:"end_time"`
	RoomId         openapi_types.UUID `json:"room_id"`
	StartTime      time.Time          `json:"start_time"`
	Title          string             `json:"title"`
}

// Bookings defines model for Bookings.
type Bookings = []Booking

// Error defines model for Error.
type Error struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status string `json:"status"`
}

// Room defines model for Room.
type Room struct {
	Capacity  int                `json:"capacity"`
	CreatedAt *time.Time         `json:"created_at,omitempty"`
	Equipment []string           `json:"equipment"`
	Floor     int                `json:"floor"`
	Id        openapi_types.UUID `json:"id"`
	IsActive  bool               `json:"is_active"`
	Name      string             `json:"name"`
	UpdatedAt *time.Time         `json:"updated_at,omitempty"`
}

// RoomCreateRequest defines model for RoomCreateRequest.
type RoomCreateRequest struct {
	Capacity  int      `json:"capacity"`
	Equipment []string `json:"equipment"`
	Floor     int      `json:"floor"`
	IsActive  bool     `json:"is_active"`
	Name      string   `json:"name"`
}

// RoomStats defines model for RoomStats.
type RoomStats struct {
	BusiestDay    openapi_types.Date `json:"busiest_day"`
	RoomId        openapi_types.UUID `json:"room_id"`
	RoomName      string             `json:"room_name"`
	TotalBookings int                `json:"total_bookings"`
	TotalHours    float32            `json:"total_hours"`
}

// RoomStatsList defines model for RoomStatsList.
type RoomStatsList = []RoomStats

// Rooms defines model for Rooms.
type Rooms = []Room

// Limit defines model for Limit.
type Limit = int

// Offset defines model for Offset.
type Offset = int

// AuthError defines model for AuthError.
type AuthError = Error

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// PageNotFound defines model for PageNotFound.
type PageNotFound = Error

// ServerError defines model for ServerError.
type ServerError = Error

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// ListBookingsParams defines parameters for ListBookings.
type ListBookingsParams struct {
	// RoomId Filter bookings by room id
	RoomId *openapi_types.UUID `form:"room_id,omitempty" json:"room_id,omitempty"`

	// DateFrom Filter bookings starting from this date and time
	DateFrom *time.Time `form:"date_from,omitempty" json:"date_from,omitempty"`

	// DateTo Filter bookings up to this date and time
	DateTo *time.Time `form:"date_to,omitempty" json:"date_to,omitempty"`

	// Limit Maximum number of items to return
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of items to skip
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetMyBookingsParams defines parameters for GetMyBookings.
type GetMyBookingsParams struct {
	// Limit Maximum number of items to return
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of items to skip
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListRoomsParams defines parameters for ListRooms.
type ListRoomsParams struct {
	// Floor Filter rooms by floor
	Floor *int `form:"floor,omitempty" json:"floor,omitempty"`

	// MinCapacity Filter rooms by minimum capacity
	MinCapacity *int `form:"min_capacity,omitempty" json:"min_capacity,omitempty"`

	// Limit Maximum number of items to return
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of items to skip
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
}

// CreateBookingJSONRequestBody defines body for CreateBooking for application/json ContentType.
type CreateBookingJSONRequestBody = BookingCreateRequest

// CreateRoomJSONRequestBody defines body for CreateRoom for application/json ContentType.
type CreateRoomJSONRequestBody = RoomCreateRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get room analytics
	// (GET /analytics/rooms)
	GetRoomAnalytics(w http.ResponseWriter, r *http.Request)
	// List bookings
	// (GET /bookings)
	ListBookings(w http.ResponseWriter, r *http.Request, params ListBookingsParams)
	// Create booking
	// (POST /bookings)
	CreateBooking(w http.ResponseWriter, r *http.Request)
	// Get my bookings
	// (GET /bookings/my)
	GetMyBookings(w http.ResponseWriter, r *http.Request, params GetMyBookingsParams)
	// Cancel booking by id
	// (DELETE /bookings/{id})
	CancelBooking(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Check server health
	// (GET /health)
	CheckServerHealth(w http.ResponseWriter, r *http.Request)
	// List rooms
	// (GET /rooms)
	ListRooms(w http.ResponseWriter, r *http.Request, params ListRoomsParams)
	// Create room
	// (POST /rooms)
	CreateRoom(w http.ResponseWriter, r *http.Request)
	// Delete room by id
	// (DELETE /rooms/{id})
	DeleteRoom(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Get room by id
	// (GET /rooms/{id})
	GetRoom(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Get room analytics
// (GET /analytics/rooms)
func (_ Unimplemented) GetRoomAnalytics(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List bookings
// (GET /bookings)
func (_ Unimplemented) ListBookings(w http.ResponseWriter, r *http.Request, params ListBookingsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create booking
// (POST /bookings)
func (_ Unimplemented) CreateBooking(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get my bookings
// (GET /bookings/my)
func (_ Unimplemented) GetMyBookings(w http.ResponseWriter, r *http.Request, params GetMyBookingsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Cancel booking by id
// (DELETE /bookings/{id})
func (_ Unimplemented) CancelBooking(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Check server health
// (GET /health)
func (_ Unimplemented) CheckServerHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List rooms
// (GET /rooms)
func (_ Unimplemented) ListRooms(w http.ResponseWriter, r *http.Request, params ListRoomsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create room
// (POST /rooms)
func (_ Unimplemented) CreateRoom(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete room by id
// (DELETE /rooms/{id})
func (_ Unimplemented) DeleteRoom(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get room by id
// (GET /rooms/{id})
func (_ Unimplemented) GetRoom(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetRoomAnalytics operation middleware
func (siw *ServerInterfaceWrapper) GetRoomAnalytics(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRoomAnalytics(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListBookings operation middleware
func (siw *ServerInterfaceWrapper) ListBookings(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListBookingsParams

	// ------------- Optional query parameter "room_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "room_id", r.URL.Query(), &params.RoomId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "room_id"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "room_id", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "date_from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "date_from", r.URL.Query(), &params.DateFrom, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "date_from"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "date_from", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "date_to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "date_to", r.URL.Query(), &params.DateTo, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "date_to"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "date_to", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "offset"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListBookings(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateBooking operation middleware
func (siw *ServerInterfaceWrapper) CreateBooking(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateBooking(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMyBookings operation middleware
func (siw *ServerInterfaceWrapper) GetMyBookings(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetMyBookingsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "offset"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMyBookings(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CancelBooking operation middleware
func (siw *ServerInterfaceWrapper) CancelBooking(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CancelBooking(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CheckServerHealth operation middleware
func (siw *ServerInterfaceWrapper) CheckServerHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CheckServerHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRooms operation middleware
func (siw *ServerInterfaceWrapper) ListRooms(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListRoomsParams

	// ------------- Optional query parameter "floor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "floor", r.URL.Query(), &params.Floor, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "floor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "floor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "min_capacity" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "min_capacity", r.URL.Query(), &params.MinCapacity, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "min_capacity"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "min_capacity", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "offset"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRooms(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateRoom operation middleware
func (siw *ServerInterfaceWrapper) CreateRoom(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateRoom(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteRoom operation middleware
func (siw *ServerInterfaceWrapper) DeleteRoom(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteRoom(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRoom operation middleware
func (siw *ServerInterfaceWrapper) GetRoom(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRoom(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/analytics/rooms", wrapper.GetRoomAnalytics)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/bookings", wrapper.ListBookings)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/bookings", wrapper.CreateBooking)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/bookings/my", wrapper.GetMyBookings)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/bookings/{id}", wrapper.CancelBooking)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.CheckServerHealth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/rooms", wrapper.ListRooms)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/rooms", wrapper.CreateRoom)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/rooms/{id}", wrapper.DeleteRoom)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/rooms/{id}", wrapper.GetRoom)
	})

	return r
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fptb9s48v8qBP9/oG/kWHKcbOt3aXdz19s+oS2wwAWGwUjjmFtJVEkqW1/g734gqQfSpizLTq4HXN5F",
	"MTn6ceY3w3nQA45ZVrAccinw7AEXhJMMJHD99I5mVKo/EhAxp4WkLMcz/J78oFmZobzMboEjtkRUQiaQ",
	"ZIiDLHmOAww/SFakgGeTMMBU7fpeAl/jAOckAzzDqZYdYBGvICPmJUtSptJsyWiu3oFnUYDlulA7aC7h",
	"DjjebAL8cbkU4IH2YReS+EYLG1AHHmYkegHZeEIPnk2AOYiC5QK03q5KufqNc8bVQ8xyCbnGSooipTFR",
	"WMd/CgX4ocWlViaAZ9MwCnAGQpA79RYli3H6L70LgZa6sVH+P4clnuH/G7eWHJtfxdiA0ABdPXVIfU2S",
	"z/C9BCGPQx7ayF+TBNXSTke8Je0Ny5cpjY/E+crBydg3mt+huBZ5Otg3lqhrxm9pkkB+HNRzG2or63SM",
	"jqxP5A4+MHnNyjw5DufUxqnEoQ9MIiPwdLC7Ar8Avwd+tJdduFx9m0vgOUmREYt+eyQ/65DbCNbhoiKg",
	"jr+cFcAlNXGESAl5AiAWMSvN4ZqDRPtjZIBjDkRCsiDuPjwJJ5ej8HIUXX4NX83Ow1kY/hMHeMl4ppbi",
	"hEgYSZoBbqQKyRW+7dPZUq8ZR1dcQE7Xvn2QJwstswtKFM3CYVBo4gq7uAjh5TQMRzB5dTuaRsl0RH6J",
	"LkfT6eXlxcV0GoZhaAsvS5r45HLGssURwieHCBeScNmjiXCoJoQkstSEgVzR4UZ5w5LyDBSGmOQxpKn5",
	"m6n3SUjw3LoRneU70iWV6Rba9wBS/epZXRbJ47OuFMCPMcl5v0n01f29pBwSpTi9pGZA++JaC44BLVY3",
	"Ngh2fNZxREc/8wYMu/0TzGVRhYI3eot1FffGhSZXiSzDXvTFiE53/gPgW7pGRUryXN2NWbfFn8C1j3XB",
	"6Ke5oMdJvgLJ0KdKgTjAGfnxDvI7ucKzyYWxTP0c9dGyZeR+Hu6hlCaOTor7LrP6Oto0wgjnZK2em+vW",
	"5aO5Uh88BGtu2IeeE2oR7XrfQf4OJJWrz1WivYvCCoONET7+3uvy1TbfGz8zlnlOSwoSU7l+9Os4CocG",
	"RnWMIoOt1OBGAVZnYBwH+K8VlXDLCFf0uacJsIWK9+rADR12+bxl+GXKjOHtA+8e8qnuZCoWJJb03nUx",
	"yUtoFt8ylgLRyayp6BwacJLfAdL2PO7SGmob372icQUtf2q12na0z9pFyZ7bwcvPSR8/fyKVJl4qPaXJ",
	"t6zzWIb5IknVRnEMclsKCkIuErLu4tc2qx7zVjw86x3sOJJJki5urRumzT28VjUbVqzk7upoctay0vSV",
	"9lyCLdgdCO4rAkf3e832jhpfOuiKbI3tIbj6UQwStStF5SkQl5zK9Re1sCISEA78qlQ5Q/10XVv2H398",
	"rbtX2jn0r63RVlIWpkKl+ZLtds6uPr1FS8bRiyrVGyklixdNymFWiAJivawAOVKhwbP+HrgwMsOz8CxS",
	"h2MF5KSgeIbPz8IzlZYXRK70mcYkJ+la0liMea24O9PaUz6ky/i3CZ7hv4FUurqql+OtptskDIc0Am62",
	"/NJ1xsbXDnUwy3+2nWbLR6Jwyw2iyWZ+aKPBpaun4fCljGMQYlmmqNYO+ovKFVIAUaNrZZQLozDf6xrF",
	"ju02i2ZlmWWEr409toUGWBJ1xBvc/m8e4B8jzlIw/08ymuO5kjS2w4bX4uqMr1vHtnvTN9v0vaapBI5q",
	"meh2bcDpeDG4jvc1iNvw05qqt7jsg6nTeFVgLTnLkFxRgVT4RyRPUJ3ce2toq0LxgVVCFkqmH+7exKUP",
	"c1kgyQ7G+sthWCU7CqmPvC1PxmaAccDCap6gHPHEoLJTm0du7t9q5uJrNGk1s9OctdppbYndVVcPDlWH",
	"bpi4tWZnmVwXX24vqbo52n6RnWl3aaLp9hzW4jk8eDaxZEjcTKmQiC0b+qvIOT0kclqzFL0l6t/Szo30",
	"jvP+HU4TfxpO+3c4nX696VX/JnueceK1oYI6stO16sZo/jXfBLhgwnMfmLqnbk+Y5BDUFZGsh40AfD7q",
	"0qG7/9Xvi4P8KzrQv2pXcrtKm4HUdyvHjZthq9pqsxP/otNV6w9/biP4fzn8uZoYGv4GUmBQ8KssV/vr",
	"c+w7LfYZ92u06Qt+TrasqLCVLI+z9b4K6f26O2F+zpWec6WnzZXiknPIJVKoXoitlOnpY8AjFLTZen9u",
	"0uueDzTZmOZKChI8OYyexto5jONB093GTKvtdI2aYa4bko+IfaeGMg2kRqHKbVMAe7O5fYV7/fXN8EI9",
	"rOvJgshVW06aDqGT1Qwp2RXg8UqPmjoD7ZsVxN+MbsxQ6sReVDu7wh9/P/xG3xqI+TzVfHVCBTIncjuL",
	"eHYzd2yqjoWE2bOqD1abVKyFhKzi+/5WncrxTRf0sK6NlqY41LTdrdGAr2VQr2v1tPuNYN+7qnEIsrr+",
	"9uDc99qM5gtrefv2/V8r/jdeve2QaE+Cbg+9rPmQPRSaNwOdybCb1ZrvGBf1Nk+7EuYW2bDe6XG1v2H7",
	"c/J7euHPq6hQBxXz3FfyV2Q4ut53yN5B5L3TTYviB9B2M4SRT1+SW6cPT/L1Q1X0M6LAEJUfVQLzyrLP",
	"IeDk+pdXgzE3BnTOifTvvYn1r/r/TaQYlFUbmbaN//MJtcFvhlbb2fQ+DQV7p6UnJ6bPweOU4PEcNB5x",
	"ztzhFX0F5ufjxsBPVV269Zf7TcfNXGezWhW+o/wK91V5pnjN0+qzjtl4nLKYpCsm5Oxl+DIck4KO7yO8",
	"mW/+HQAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
